import React from 'react';
import { 
  Users, 
  Calendar, 
  FileSpreadsheet, 
  Banknote, 
  Activity, 
  TrendingUp, 
  Sparkles, 
  Download, 
  CheckCircle,
  Clock
} from 'lucide-react';
import { mockReportsData } from '../data/mockReportsData';

const KpiCard = ({ title, value, sub, icon: Icon, color, bg }) => {
  return (
    <div className="bg-white p-5 rounded-2xl border border-slate-100 shadow-sm flex items-center justify-between hover:shadow-md transition-all duration-200 group">
      <div className="space-y-1">
        <span className="text-[10px] text-slate-400 font-bold uppercase tracking-wider">{title}</span>
        <p className="text-xl font-black text-slate-805 tracking-tight group-hover:text-indigo-655 transition-colors">{value}</p>
        <span className="text-[10px] text-slate-500 font-bold block">{sub}</span>
      </div>
      <div className={`p-3 rounded-xl ${bg} ${color} group-hover:scale-105 transition-transform duration-200`}>
        <Icon className="h-5 w-5" />
      </div>
    </div>
  );
};

const ReportsDashboard = () => {
  return (
    <div className="space-y-6">
      
      {/* 6 Executive KPI summary cards */}
      <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-4">
        <KpiCard 
          title="Total Employees" 
          value={mockReportsData.kpis.totalEmployees} 
          sub="3 new hires" 
          icon={Users} 
          color="text-indigo-600" 
          bg="bg-indigo-50" 
        />
        <KpiCard 
          title="Avg Attendance" 
          value={mockReportsData.kpis.avgAttendance} 
          sub="+1.2% this cycle" 
          icon={Calendar} 
          color="text-emerald-600" 
          bg="bg-emerald-50" 
        />
        <KpiCard 
          title="Leave Utilized" 
          value={mockReportsData.kpis.leaveUtilization} 
          sub="40.0% used" 
          icon={FileSpreadsheet} 
          color="text-amber-600" 
          bg="bg-amber-50" 
        />
        <KpiCard 
          title="Payroll Cost" 
          value={mockReportsData.kpis.payrollExpense} 
          sub="June release" 
          icon={Banknote} 
          color="text-rose-600" 
          bg="bg-rose-50" 
        />
        <KpiCard 
          title="Avg Performance" 
          value={mockReportsData.kpis.departmentPerformance} 
          sub="Q2 KPI target" 
          icon={Activity} 
          color="text-blue-600" 
          bg="bg-blue-50" 
        />
        <KpiCard 
          title="Attrition Rate" 
          value={mockReportsData.kpis.attritionRate} 
          sub="CTC threshold check" 
          icon={TrendingUp} 
          color="text-purple-600" 
          bg="bg-purple-50" 
        />
      </div>

      {/* AI-style recommendation insights */}
      <div className="bg-white p-5 rounded-2xl border border-slate-100 shadow-sm space-y-4">
        <div className="flex items-center gap-2 border-b border-slate-50 pb-2.5">
          <Sparkles className="h-4.5 w-4.5 text-indigo-600 animate-pulse" />
          <h3 className="text-xs font-bold text-slate-800 uppercase tracking-wider">AI HR Insights Advisory</h3>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {mockReportsData.insights.map((ins, i) => (
            <div 
              key={i} 
              className={`p-3.5 rounded-xl border text-xs leading-relaxed ${
                ins.type === 'positive' ? 'bg-emerald-50 border-emerald-100 text-emerald-800' :
                (ins.type === 'warning' ? 'bg-amber-50 border-amber-100 text-amber-850' : 'bg-slate-50 border-slate-200/60 text-slate-700')
              }`}
            >
              <div className="flex items-start gap-2.5">
                <span className="mt-0.5 font-bold">💡</span>
                <span>{ins.message}</span>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Recent reports list table */}
      <div className="bg-white p-5 rounded-2xl border border-slate-100 shadow-sm space-y-4">
        <div className="border-b border-slate-50 pb-2.5">
          <h3 className="text-xs font-bold text-slate-800 uppercase tracking-wider">Recent Reports Logs</h3>
        </div>

        <div className="overflow-x-auto">
          <table className="min-w-full divide-y divide-slate-100 text-left text-xs">
            <thead className="bg-slate-50 text-slate-400 font-bold uppercase tracking-wider">
              <tr>
                <th className="px-4 py-3">Report Name</th>
                <th className="px-4 py-3">Generated By</th>
                <th className="px-4 py-3">Date</th>
                <th className="px-4 py-3">Status</th>
                <th className="px-4 py-3 text-right pr-6">Download</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100 text-slate-705 bg-white font-semibold">
              {mockReportsData.recentReports.map((rep, idx) => (
                <tr key={idx} className="hover:bg-slate-50/50 transition-colors">
                  <td className="px-4 py-3 font-bold text-slate-800">{rep.name}</td>
                  <td className="px-4 py-3 text-slate-500">{rep.createdBy}</td>
                  <td className="px-4 py-3 text-slate-500 font-mono">{rep.date}</td>
                  <td className="px-4 py-3">
                    <span className="inline-flex items-center gap-1 text-[10px] font-bold text-emerald-600 bg-emerald-50 px-2 py-0.5 rounded-full border border-emerald-100/50">
                      <CheckCircle className="h-3 w-3" />
                      {rep.status}
                    </span>
                  </td>
                  <td className="px-4 py-3 text-right pr-4">
                    <button 
                      onClick={() => alert(`Downloading spreadsheet: ${rep.name}`)}
                      className="p-1 hover:bg-slate-100 border border-slate-200 rounded-lg text-slate-550 transition cursor-pointer"
                      title="Download Sheet"
                    >
                      <Download className="h-4 w-4" />
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

    </div>
  );
};

export default ReportsDashboard;
